Clean up, add some feature, add warning barrier
MrLoLf/HoneygainAutoClaim pull request #12
Opened 2023-12-03 13:29 UTC by gorouflex

@MrLoLf I added some warning to prevent some users enter their email, pass or Token to 2 workflows file

2023-12-03 16:56 UTC, MrLoLf requested changes
If you restore the requirements.txt, I'll can merge it. It looks good too me. But those are great additions, thanks a lot.

2023-12-03 16:56 UTC, MrLoLf commented on requirements.txt
Could you please restore this file, as it's needed for the local installation with python.

2023-12-03 23:06 UTC, gorouflex commented on requirements.txt
done

2023-12-04 13:59 UTC, MrLoLf approved these changes
Looks Good Thanks

2023-12-04 13:59 UTC, merged