change cfu on github actions
MrLoLf/HoneygainAutoClaim pull request #18
Opened 2024-01-05 09:42 UTC by gorouflex

This will only check the `main.py` file, not the whole repository. Therefore, any changes outside the `main.py` file will not affect this CFU feature (#16)

2024-01-05 09:53 UTC, gorouflex commented
i'm also add a feature that if this script run on GitHub Actions, after complete the process than will delete the Config folder ( i don't know if it's useful or not? )

2024-01-11 13:26 UTC, MrLoLf requested changes
It would be great to see, which exception you are trying to catch. Please add this in to the except and I'll be happy to merge this.

2024-01-11 13:26 UTC, MrLoLf commented on main.py
> +       except:
It would be great to see, which exception you are trying to catch. Please add this in to the except and I'll be happy to merge this.

2024-01-11 13:31 UTC, gorouflex commented
@MrLoLf Can you explain more? I still don't know what do you mean

2024-01-11 13:43 UTC, MrLoLf commented
> @MrLoLf Can you explain more? I still don't know what do you mean

Yeah, no problem. It is very common to specify which error you are trying to catch with the except. So people that read this code understand, that this error could occur and when some other error was thrown in the except it wouldn't be handled by accident. So it's easier to spot bugs. When done with the correct error handling, it should like this. 
```python
try:
        urls_conf: dict[str, str] = {'login': cfg.get('Url', 'login'),
                                     'pot': cfg.get('Url', 'pot'),
                                     'balance': cfg.get('Url', 'balance'),
                                     'achievements': cfg.get('Url', 'achievements'),
                                     'achievement_claim': cfg.get('Url', 'achievement_claim')}
    except configparser.NoOptionError:
        # something to do on the exception here
```
Note the specified Error on the except.

2024-01-11 13:45 UTC, gorouflex commented
Ok i’ll do it later

2024-01-12 04:16 UTC, gorouflex commented
@MrLoLf Done

2024-01-12 08:04 UTC, merged